export const loadingPhrases = [
    'Tapping mana',
    'Summoning Saprolings',
    'Casting at instant speed',
    'I\'ll allow it',
    'Planeshifting',
    'Drawing a new hand',
    'Just Loading',
    'Meeting my rate limit',
    'Finding your new favorite',
    'Competing with EDH Rec',
    'Moving to main phase',
    'Shuffling Kozilek',
    'Rolling up the elves',
    'Flinging goblins',
    '<3ing the cards',
    'Searching through grandpa\'s deck',
    'Bolting the 🐓',
    'Pulling in more IPs',
    'Flying through the storm',
    'Blocking with squirrels',
    'Cooking with Asmoranomardicadaistinaculdacar',
    'Cooking with Gyome',
    'Adding 3 mana',
    'Cutting lands',
    'Paying the 1',
    'Hating bears',
    'Admiring Drawdmaws',
    'Chilling with Chillerpillar',
    'Finding something new',
    'Tempted to discover',
    'Traversing the outlands',
    'Adding loyalty counters',
    'Plowing the swords',
    'Almost there',

]