export const loadingPhrases = [
    'Tapping mana',
    'Summoning Saprolings',
    'Unstacking the stack',
    'Holding 2 blue mana',
    'Planeshifting',
    'Drawing a new hand',
    'Just Loading',
    'Meeting my rate limit',
    'Finding your new favorite',
    'Compeating with EDH Rec',
    'Moving to main phase',
    'Shuffling Kozilek',
    'Rolling up the elves',
    'Flinging goblins',
    'Assembling the web workers',
    'Searching through grandpa\'s deck',
    'Bolting the 🐓',
    'Pulling in more IPs',
    'Flying through the storm',
    'Blocking with squirrels',
    'Cooking with Asmoranomardicadaistinaculdacar',
    'Cooking with Gyome',
    'Losing the coin flip',
    'Cutting lands',
    'Paying the 1',
    'Hating bears',
    'Admiring Drawdmaws',
    'Chilling with Chillerpillar',
    'Finding something new',
    'Discovering something new',
    'Traversing the outlands',
    'Adding loyalty counters',
    'Plowing the swords',
    'Almost there',
    ''
]

export const rareQuotes = [
    'Sh*tting on an Iphone'
]