export interface CardTagObject {
    annotation: string | null,
    createdAt: string,
    creatorId: string,
    foreignKey: string,
    id: string,
    pendingRevisions: boolean,
    status: string,
    subjectId: string,
    tag: {
        ancestorTags: TagInformation[],
        category: boolean,
        createdAt: string,
        creatorId: string,
        id: string,
        name: string,
        namespace: string,
        pendingRevisions: boolean,
        slug: string,
        status: string,
        type: string,
    },
    category: boolean,
    name: string,
    namespace: string,
    slug: string,
    type: string,
    weight: string,
}

export interface TagInformation {
    category: boolean,
    createdAt: string,
    creatorId: string,
    id: string,
    name: string,
    namespace: string,
    pendingRevisions: boolean,
    slug: string,
    status: string,
    type: string,
}

export interface ScryfallCardObject extends RawScryfallCardObject {
    imageUrl: string;
    tags: CardTagObject[],
    showingTags: boolean,
}

export interface RawScryfallCardObject {
    artist: string,
    artist_ids: string[],
    booster: boolean
    border_color: string, 
    card_back_id: string,
    card_faces: ScryfallCardObject[],
    cardmarket_id: number,
    cmc: number,
    collector_number: string, 
    color_identity: string[],
    colors: string[],
    digital: boolean,
    edhrec_rank: number,
    finishes: string[],
    flavor_text: string,
    foil: boolean,
    frame: string,
    full_art: boolean,
    games: string[],
    highres_image: boolean,
    id: string,
    illustration_id: string,
    image_status: string,
    image_uris: any,
    keywords: string[],
    lang: string,
    layout: string,
    legalities: any,
    mana_cost: string,
    multiverse_ids: number[],
    name: string,
    nonfoil: boolean, 
    object: string,
    oracle_id: string,
    oracle_text: string,
    oversized: boolean,
    prices: any,
    prints_search_uri: string, 
    produced_mana: string[],
    promo: boolean,
    purchase_uris: any,
    rarity: string,
    related_uris: any,
    released_at: string,
    reprint: boolean,
    reserved: boolean,
    rulings_uri: string,
    scryfall_set_uri: string,
    scryfall_uri: string,
    set: string,
    set_id: string,
    set_name: string,
    set_search_uri: string,
    set_type: string,
    set_uri: string,
    showingTags: boolean,
    story_spotlight: boolean,
    tcgplayer_id: number,
    textless: boolean,
    type_line: string,
    uri: string,
    variation: boolean,
}