export interface CardTagObject {
    annotation: string | null,
    createdAt: string,
    creatorId: string,
    foreignKey: string,
    id: string,
    pendingRevisions: boolean,
    status: string,
    subjectId: string,
    tag: {
        ancestorTags: any[],
        category: boolean,
        createdAt: string,
        creatorId: string,
        id: string,
        name: string,
        namespace: string,
        pendingRevisions: boolean,
        slug: string,
        status: string,
        type: string,
    }
    category: boolean,
    name: string,
    namespace: string,
    slug: string,
    type: string,
    weight: string,
}